server:
  port: 8080
  servlet:
    context-path: /clothing-store

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cloth"
    username: root
    password: Nghiep2004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true